version: '3.8'

services:
  # Backend Flask API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - TLDV_API_KEY=${TLDV_API_KEY}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_SERVICE_ACCOUNT_PATH=/app/firebase-service-account.json
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key}
    volumes:
      - ./backend:/app
      - ./firebase-service-account.json:/app/firebase-service-account.json:ro
    depends_on:
      - redis
    restart: